[KAJ-1065] VDI Mac 1.2: Update Customer Documentation
Kandy-IO/kandy-distant-vdi pull request #10
Opened 2022-03-11 20:07 UTC by pegnovi

** Story **
[KAJ-1065](https://kandyio.atlassian.net/browse/KAJ-1065) VDI Mac 1.2: Update Customer Documentation
[KAJ-1077](https://kandyio.atlassian.net/browse/KAJ-1077) Documentation - Add documentation for DistantBrowser openOnly flag

** Description **
Updated changelog for Mac Release ver 1.1.4 and also added stuff under "Unreleased" section.

2022-03-15 16:34 UTC, pegnovi commented on mac/CHANGELOG.md
> +- `openOnly` flag can be used on the DistantBrowser executable which will run the initial one-time loading of the CEF library and exits immediatly. To be used by customer's install script. `KAJ-954`
I'm going to move this to be under release 1.1.3 because it fits there based on the date the PR was merged.

2022-03-16 01:38 UTC, jfmoron requested changes

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- KandyHID: Add flag to force use of DLL. `KAJ-1087`
this one is HID not VDI

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- `distant-remote` `close` function can now be used which allows the remote app to close the session it is associated with.  `KAJ-1064`
this is not VDI

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Moved KandyHID preload script. `KAJ-1040`
Not VDI

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Distant Tracker updated to work with electron context isolation. `KAJ-1031`
Not VDI

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- All HID devices can now be accessed by WebHID. `KAJ-890`
This one is VDI but Linux only

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Distant Tracker: Handle vertically stacked monitors. `KAJ-993`
Not VDI

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Send message to remote app when window closes. `KAJ-1039`
this one should be in the fixed column, even if it's a story.

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Browser messages get buffered to prevent lost messages. `KAJ-1043`
This one was a bug JPMC raised that I had added above as KAJ-1023

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Instantiate one Mac window per session. `KAJ-1038`
this is more of an internal task

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Trailing directory separator in log path causes issues on some machines. `KAJ-1160`
This one is related to 1157 raised by JPMC, so better to put this one

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Citrix session has to be restarted for the RTC app to work after Simulating Browser Crash. `KAJ-1128`
we need to rename this one, no one knowns about the RTC app

2022-03-16 01:38 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Distant window jumps to the opposing screen when the Citrix window displayed on that screen is focused upon. `KAJ-1050`
this one was reverted because it caused some regression

2022-03-16 01:38 UTC, jfmoron commented on mac/README.md
> +- Distant messges sent too quickly causes issues on M1. `KAJ-1023`
this is a bug that was fixed. you can remove

2022-03-16 01:38 UTC, jfmoron commented on mac/README.md
>  ## 2. Limitations
change the title to match linux title

2022-03-16 01:40 UTC, jfmoron commented on mac/README.md
>  ## 2. Limitations
Also let's add a line to explain that there are some issues when Mac is in full screen mode.

2022-03-17 17:44 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Citrix session has to be restarted for the RTC app to work after Simulating Browser Crash. `KAJ-1128`
Renamed to 
`- Orchestrator does not handle browser death correctly causing recovery mechanism to not run. `KAJ-1128``

2022-03-17 17:44 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Trailing directory separator in log path causes issues on some machines. `KAJ-1160`
Changed to KAJ-1157.

2022-03-17 17:44 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Browser messages get buffered to prevent lost messages. `KAJ-1043`
Changed it to KAJ-1023.

2022-03-17 17:45 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Distant Tracker: Handle vertically stacked monitors. `KAJ-993`
Removed.

2022-03-17 17:45 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Distant Tracker updated to work with electron context isolation. `KAJ-1031`
Removed.

2022-03-17 17:45 UTC, pegnovi commented on mac/CHANGELOG.md
> +- KandyHID: Add flag to force use of DLL. `KAJ-1087`
Removed.

2022-03-17 17:46 UTC, pegnovi commented on mac/README.md
> +- Distant messges sent too quickly causes issues on M1. `KAJ-1023`
Removed.

2022-03-17 17:59 UTC, pegnovi commented on mac/CHANGELOG.md
> +- All HID devices can now be accessed by WebHID. `KAJ-890`
Removed.

2022-03-18 17:04 UTC, jfmoron approved these changes

2022-03-18 17:04 UTC, merged