[KAJ-1201] & [KAJ-1195] Windows & Mac 1.7.0 Documentation
Kandy-IO/kandy-distant-vdi pull request #15
Opened 2022-06-08 20:53 UTC by pegnovi

## Story
[KAJ-1201](https://kandyio.atlassian.net/browse/KAJ-1201) Windows 1.7.0: Documentation
[KAJ-1195](https://kandyio.atlassian.net/browse/KAJ-1196) Mac 1.7.0: Documentation

## Description
Updated Changelogs for Windows & Mac.
Also updated changelog for Elux & its readme.

2022-06-15 01:21 UTC, jfmoron requested changes

2022-06-15 01:21 UTC, jfmoron commented on eLux/CHANGELOG.md
> +- Distant Tracker: Fixed address exception when exiting fullscreen. `KAJ-1189`
you should remove tracker related jira from here

2022-06-15 01:21 UTC, jfmoron commented on eLux/CHANGELOG.md
> +- Distant Reinitialization fails during Virus Scan. `KAK-1299`
typo this should be KAJ instead of KAK

2022-06-15 01:21 UTC, jfmoron commented on mac/CHANGELOG.md
> +- Distant Reinitialization fails during Virus Scan. `KAK-1299`
KAK vs KAJ

2022-06-15 19:13 UTC, pegnovi commented on mac/CHANGELOG.md
> +- MacOS: Distant window's contents are undisturbed by intersecting Citrix preferences. `KAJ-1084`
They were related fixes. I have combined them into one log and summarized it.

2022-06-15 19:14 UTC, pegnovi commented on eLux/CHANGELOG.md
> +- Distant Tracker: Fixed address exception when exiting fullscreen. `KAJ-1189`
Removed

2022-06-15 19:14 UTC, pegnovi commented on mac/CHANGELOG.md
> +- Distant Reinitialization fails during Virus Scan. `KAK-1299`
Fixed.

2022-06-15 19:14 UTC, pegnovi commented on windows/CHANGELOG.md
> +- Distant Reinitialization fails during Virus Scan. `KAK-1299`
Fixed.

2022-06-23 19:40 UTC, jfmoron approved these changes

2022-06-23 19:41 UTC, jfmoron commented
let's wait to do the merge that we are releasing and updating the date

2022-07-04 13:14 UTC, brenthompson requested changes
just looked at elux readme for another change i'm doing

2022-07-12 23:57 UTC, jfmoron approved these changes

2022-07-12 23:57 UTC, merged