Mac: Known issue - Fullscreen must use all monitors
Kandy-IO/kandy-distant-vdi pull request #16
Opened 2022-06-24 18:21 UTC by adventurist

- Adding a known issue
- Removing "Will not fix" from previous known issue requiring Mission Control to be set to use separate spaces for each monitor

2022-06-29 15:49 UTC, brenthompson requested changes

2022-06-29 15:49 UTC, brenthompson commented on mac/README.md
> +- Fullscreen mode only functions correctly when Citrix is configured to use ALL monitors. `KAJ-1314`
I'd reword these to something less black and white, like "for proper operation...." 
"for proper operation Citrix should be configured to use all monitors"
words like "should", "may", "may not", etc are better for customer-facing docs than "only functions correctly"

2022-06-30 19:16 UTC, adventurist commented on mac/README.md
> +- Fullscreen mode only functions correctly when Citrix is configured to use ALL monitors. `KAJ-1314`
I've amended it to be a bit more customer-friendly

2022-07-05 16:02 UTC, brenthompson commented on mac/README.md
> +- Fullscreen mode with multiple monitors functions best when Mission Control's *Displays have separate Spaces* is set to the default *checked* setting
not to be too picky, but should we mention that this is in reference to remote app window? cause right now it's not clear what around Fullscreen mode doesn't work correctly

2022-07-06 15:47 UTC, brenthompson approved these changes
LGTM

2022-07-11 13:26 UTC, merged