[KAJ-1416] Document the Citrix disconnect behaviour
Kandy-IO/kandy-distant-vdi pull request #19
Opened 2022-09-16 19:37 UTC by pegnovi

[KAJ-1416](https://kandyio.atlassian.net/browse/KAJ-1416) Document the Citrix disconnect behaviour

Added documentation for Sleep & Disconnect for each OS.

2022-09-21 12:59 UTC, jfmoron requested changes
This need to be more external oriented.

2022-09-21 13:00 UTC, jfmoron commented
ex:

## 5. Sleep & Disconnect behaviour

Citrix Workspace App handles computer sleep and network disconnects somewhat differently on each os. This has some impact on Distant and your Distant sessions. It is important that you application can handle these scenarios. Please refer to the sub section for more information.

 ### 5.1 On Sleep

When waking from a short sleep (less than 3 minutes) the CWA will resume and your Distant session will be available.

When waking from a long sleep (more than 3 minutes) :

     - The CWA may exit in which case all Distant session are closed.
     - The CWA may exit and restart in which case all distant session may be reloaded, or closed.
 
### 5.2 On network Disconnect

When the network disconnect, the CWA will prompt asking to reconnect. When reconnecting, the distant session will not be available.

2022-09-21 19:03 UTC, pegnovi commented
> ex:
> 
> ## 5. Sleep & Disconnect behaviour
> Citrix Workspace App handles computer sleep and network disconnects somewhat differently on each os. This has some impact on Distant and your Distant sessions. It is important that you application can handle these scenarios. Please refer to the sub section for more information.
> 
> ### 5.1 On Sleep
> When waking from a short sleep (less than 3 minutes) the CWA will resume and your Distant session will be available.
> 
> When waking from a long sleep (more than 3 minutes) :
> 
> ```
>  - The CWA may exit in which case all Distant session are closed.
>  - The CWA may exit and restart in which case all distant session may be reloaded, or closed.
> ```
> 
> ### 5.2 On network Disconnect
> When the network disconnect, the CWA will prompt asking to reconnect. When reconnecting, the distant session will not be available.

Updated as requested.
JF wants someone else to review. Mainly to check grammar.

2022-09-22 19:50 UTC, brenthompson approved these changes
a few minor comments, but fine as is

2022-09-22 19:50 UTC, brenthompson commented on eLux/README.md
> +When waking from a short sleep (less than 3 minutes) the CWA will resume and your Distant session will be available.
i'd add
- (less than "around" or "approximately" 3 minutes) cause it may not be exact, and it's out of our control.
- `your original Distant session` for clarity

2022-09-22 19:50 UTC, brenthompson commented on eLux/README.md
> +CWA (Citrix Workspace App) handles computer sleep and network disconnects somewhat differently on each OS. This has some impact on Distant and your Distant sessions. It is important that your applica
subsections is one word

2022-09-22 19:50 UTC, brenthompson commented on eLux/README.md
> +When reconnecting, the CWA will resume but the distant session will not be available.
`will not be available.`.... and then the user has to restart their app? Be clear on what the developer / user has to do

2022-09-22 19:50 UTC, brenthompson commented on eLux/README.md
> +When not reconnecting, then the CWA and distant session will be closed.
same comment as above

2022-09-22 19:50 UTC, brenthompson commented on mac/README.md
> +When still disconnected for more than 5 minutes, the CWA and distant session will be closed.
change 'distant' to 'Distant', be consistent

2022-09-22 19:50 UTC, brenthompson commented on windows/README.md
> +When still disconnected for more than 5 minutes, the CWA and distant session will be closed.
Distant

2022-09-23 16:38 UTC, pegnovi commented on eLux/README.md
> +When waking from a short sleep (less than 3 minutes) the CWA will resume and your Distant session will be available.
Updated.

2022-09-23 16:38 UTC, pegnovi commented on eLux/README.md
> +CWA (Citrix Workspace App) handles computer sleep and network disconnects somewhat differently on each OS. This has some impact on Distant and your Distant sessions. It is important that your applica
Updated.

2022-09-23 16:38 UTC, pegnovi commented on eLux/README.md
> +When reconnecting, the CWA will resume but the distant session will not be available.
Updated.

2022-09-23 16:38 UTC, pegnovi commented on eLux/README.md
> +When not reconnecting, then the CWA and distant session will be closed.
Updated.

2022-09-23 16:38 UTC, pegnovi commented on mac/README.md
> +When still disconnected for more than 5 minutes, the CWA and distant session will be closed.
Updated.

2022-09-23 16:38 UTC, pegnovi commented on windows/README.md
> +When still disconnected for more than 5 minutes, the CWA and distant session will be closed.
Updated.

2022-09-26 20:28 UTC, jfmoron approved these changes
one small item then good to go.

2022-09-26 20:28 UTC, jfmoron commented on eLux/README.md
> +CWA (Citrix Workspace App) handles computer sleep and network disconnects somewhat differently on each OS. This has some impact on Distant and your Distant sessions. It is important that your applica
Maybe in the : "somewhat differently on each OS" be we can add "when a VDI session is connected"

2022-09-26 20:39 UTC, pegnovi commented on eLux/README.md
> +CWA (Citrix Workspace App) handles computer sleep and network disconnects somewhat differently on each OS. This has some impact on Distant and your Distant sessions. It is important that your applica
Updated.

2022-09-26 20:41 UTC, merged