Adding Windows 10 support
Kandy-IO/kandy-distant-vdi pull request #3
Opened 2021-03-17 22:44 UTC by jfmoron

2021-03-19 20:25 UTC, brenthompson requested changes

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +In the event that 2 simultanious VDI sessions are opened, only the first session will be able to use the Distant driver.
simultaneous

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +Windows 10 64 bit.
You probably want to specify Windows 10 Enterprise and Professional, or refer to Citrix's support page, because Citrix does not currently support Home.

I had to add this long disclaimer into the kandy-hid docs for Windows:

At this time, Citrix does not formally support the use of the Citrix Workspace app in Windows Home Edition.  Citrix is currently evaluating support for Home Editions. A formal tracking number for this activity has been requested of Citrix.

For this doc, you could reduce it to: 
At this time, Citrix does not formally support the use of the Citrix Workspace app in Windows Home Edition

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +In order for the Driver to be loaded by The Cirtirx Workspace App it needs to be added to the Windows Registry
typo `Citrix`. `the` should not be capitalized

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +1. Locate the VirtualDriverEx string REG_SZ value in the *HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Citrix\ICA Client\Engine\Configuration\Advanced\Modules\ICA 3.0* key. This setting is a coma separate
- typo `coma` should be `comma`
- `Sets the value` should be `Set the value`

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +2. Under the *HKLM:\Software\WOW6432Node\Citrix\ICA Client\Engine\Configuration\Advanced\Modules* key, create a new key named *KandyDistant*.
there's no `:` in registry paths...

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +This section allow to set different configuration flags that affect the browser container.
`This section allows configuration flags that affect the browser container to be set`

2021-03-19 20:25 UTC, brenthompson commented on windows/README.md
> +- CommandSwitch: Command Switch arguments to be used with the browser container. Multiple command switches can be separated by a comma.
there's no mention of defaults. are there any to be highlighted? are any of the switches in the example below required?

2021-03-22 14:14 UTC, jfmoron commented on windows/README.md
> +In the event that 2 simultanious VDI sessions are opened, only the first session will be able to use the Distant driver.
fixed

2021-03-22 14:15 UTC, jfmoron commented on windows/README.md
> +Windows 10 64 bit.
added mention for home, but did not referred the RFE because it's not related really

2021-03-22 14:16 UTC, jfmoron commented on windows/README.md
> +- CommandSwitch: Command Switch arguments to be used with the browser container. Multiple command switches can be separated by a comma.
added the optional keyword,

2021-03-22 14:16 UTC, merged