KAJ-670 - Mac Documentation
Kandy-IO/kandy-distant-vdi pull request #4
Opened 2021-06-29 16:00 UTC by adventurist

# Story

https://jira.rbbn.com/browse/KAJ-670

# Description

This adds a `README` with install/setup instructions and a `CHANGELOG` for KandyDistant Virtual Driver / Plugin to be used with Citrix Workspace App for MacOS.

2021-06-29 20:32 UTC, pegnovi approved these changes
LGTM.

2021-07-08 18:59 UTC, jfmoron requested changes
Main comment is about this is a customer acting doc.

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +### 3.1 Building the Plugin and Applications
this is a customer documentation they won't build it

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +### 3.2 Signing
For signing we need to tell them what they need in the entitlements file, but we won't provide them.

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +### 3.3 Sign the Plugin
let's make this generic, remove RIBBON and the paths specific to our env

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +### 4.2 Installing Files
here make the folders generic.

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +`[KandyDistant]`
don't we need the executable path here?

2021-07-08 18:59 UTC, jfmoron commented on mac/README.md
> +- ~/Library/Application Support/Kandy/config.ini
is the config.ini relative to the app?

2021-07-08 19:00 UTC, jfmoron reviewed
You will also need to update the main page to add a link

2021-07-08 19:02 UTC, adventurist commented on mac/README.md
> +`[KandyDistant]`
I don't think so - at least, we never set it in our own Modules file

2021-07-08 19:17 UTC, adventurist commented on mac/README.md
> +### 3.1 Building the Plugin and Applications
Changed this to "preparing the installation files" in case they need to expand an archive

2021-07-08 19:17 UTC, adventurist commented on mac/README.md
> +### 3.2 Signing
we followed up on this

2021-07-08 19:17 UTC, adventurist commented on mac/README.md
> +### 3.3 Sign the Plugin
done

2021-07-08 19:18 UTC, adventurist commented on mac/README.md
> +### 4.2 Installing Files
Done

2021-07-08 20:48 UTC, jfmoron requested changes

2021-07-08 20:48 UTC, jfmoron commented on mac/README.md
> +*Note: This assumes that you are installing the Plugin from the usual build directory, and that you are NOT installing it from a mounted Apple Disk Image*
this can be removed

2021-07-09 02:39 UTC, adventurist commented on mac/README.md
> +- `~/Library/Application Support/Kandy`
changed

2021-07-09 02:39 UTC, adventurist commented on mac/README.md
> +*Note: This assumes that you are installing the Plugin from the usual build directory, and that you are NOT installing it from a mounted Apple Disk Image*
done

2021-07-14 15:55 UTC, jfmoron approved these changes

2021-07-14 15:56 UTC, merged