Documenting SessionOverwrite configuration option
Kandy-IO/kandy-distant-vdi pull request #5
Opened 2021-07-21 16:09 UTC by adventurist

No story, but corresponds to https://kandyio.atlassian.net/browse/KAJ-772

2022-02-15 17:07 UTC, brenthompson requested changes
Fix minor grammatical error

2022-02-15 17:07 UTC, brenthompson commented on windows/README.md
> +The install.ps1 script is given as an example on how to install the files, and will setup the application with some defaults path. The script needs to be run as an administrator and will install the
fix `defaults path` to `default paths`

2022-02-23 20:20 UTC, jfmoron approved these changes

2022-02-23 20:26 UTC, jfmoron approved these changes

2022-02-23 20:26 UTC, merged