updated changelogs for remaining releases
Kandy-IO/kandy-distant-vdi pull request #7
Opened 2022-02-15 00:40 UTC by jfmoron

Updated the changelings for the following releases

Mac

- 1.1.0
- 1.1.1
- 1.1.2
- 1.1.3
- 1.1.4

Windows

- 1.1.1
- 1.1.2
- 1.1.3

2022-02-15 16:41 UTC, brenthompson requested changes
one minor thing to cleanup i think

2022-02-15 16:41 UTC, brenthompson commented on mac/CHANGELOG.md
> +# 1.1.4 - 2021-12-07
not a big deal, but i noticed that the Mac changelog uses # for versions, the one for Windows uses two ##. Afaik it should be 2, but it probably doesn't matter, but it should be consistent.

2022-02-16 16:08 UTC, jfmoron commented on mac/CHANGELOG.md
> +# 1.1.4 - 2021-12-07
fixed

2022-02-17 13:43 UTC, brenthompson approved these changes
i would have put the Known Issues either in the respective readme's, or under the Release they apply to. Not sure they fit in with the statement "This change log follows [keepachangelog.com](http://keepachangelog.com/) recommendations." since it doesn't mention Known Issues or limitations. They do have a release type called Unreleased to show what's coming later, which we could use instead of Known Issues.
but, up to you. i dont think it's worth spending a lot of time on documentation no one will ever read. we can change it for future releases

2022-02-23 02:08 UTC, merged